Vagrant.configure(2) do |config|
  config.vm.box = "192.168.0.30"
  config.vm.network "public_network", bridge: "wlan0", ip: "192.168.0.30" 
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 512
  end
end