# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='T\xedtulo')),
                ('memory', models.IntegerField(verbose_name='Mem\xf3ria')),
                ('processor', models.IntegerField(verbose_name='Core')),
            ],
            options={
                'verbose_name': 'M\xe1quina Virtual',
                'verbose_name_plural': 'M\xe1quinas Virtuais',
            },
        ),
        migrations.CreateModel(
            name='StateDroplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_droplet_id', models.IntegerField(default=0, verbose_name='Id da \xfaltima VM')),
                ('ip_3', models.IntegerField(default=0, verbose_name='Pen\xfaltimo IP')),
                ('last_ip_4', models.IntegerField(default=0, verbose_name='\xdaltimo IP usado')),
                ('pool_ip', models.IntegerField(default=10, verbose_name="Total de IP's")),
                ('available_ip', models.IntegerField(default=10, verbose_name="IP's dispon\xedveis")),
            ],
            options={
                'verbose_name': 'Estado da VM',
                'verbose_name_plural': "Estados das VM's",
            },
        ),
        migrations.CreateModel(
            name='UserDroplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='Nome da VM')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('droplet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_droplet', to='vm.Droplet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_droplet', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio')),
            ],
            options={
                'verbose_name': 'Usu\xe1rio m\xe1quina',
                'verbose_name_plural': 'Usu\xe1rios m\xe1quinas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userdroplet',
            unique_together=set([('user', 'droplet')]),
        ),
    ]
