# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponivel ?')),
            ],
            options={
                'verbose_name': 'IP dispon\xedvel',
                'verbose_name_plural': "IP's dispon\xedveis",
            },
        ),
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='T\xedtulo')),
                ('memory', models.IntegerField(verbose_name='Mem\xf3ria')),
                ('processor', models.IntegerField(verbose_name='Core')),
                ('disk', models.IntegerField(default=40, verbose_name='Tamanho do disco virtual (GB)')),
            ],
            options={
                'verbose_name': 'M\xe1quina Virtual',
                'verbose_name_plural': 'M\xe1quinas Virtuais',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('name_path', models.CharField(max_length=255, unique=True, verbose_name='Nome do caminho')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='UserDroplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nome da VM')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('status', models.IntegerField(choices=[(1, 'VM inativa'), (2, 'VM ativa'), (3, 'Criando VM'), (4, 'Editando VM')], default=1, verbose_name='Status')),
                ('can_remove', models.BooleanField(default=False, verbose_name='Pode Excluir ?')),
                ('droplet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_droplet', to='vm.Droplet', verbose_name='Droplet')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_droplet', to='vm.Image', verbose_name='Imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_droplet', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio')),
            ],
            options={
                'verbose_name': 'Usu\xe1rio m\xe1quina',
                'verbose_name_plural': 'Usu\xe1rios m\xe1quinas',
            },
        ),
    ]
