# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droplet',
            name='cost',
            field=models.FloatField(default=5, verbose_name='Custo ($)'),
        ),
    ]
