# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0003_availableips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateDroplet',
        ),
        migrations.AlterField(
            model_name='userdroplet',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nome da VM'),
        ),
    ]
